# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

set: [pipefail]
shopt: [globstar]

includes:
  tool: ./tasks/tool.task.yml
  format: ./tasks/format.task.yml
  lint: ./tasks/lint.task.yml
  versions: ./tasks/versions.task.yml
  build: ./tasks/build.task.yml

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    aliases: [all]
    cmds:
    - task: tool
    - task: format
    - task: lint
    - task: versions
    - task: build

  github:actions:cache:version:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    cmds:
    # workaround: what to do when your cache key becomes corrupted
    - coreutils date +%s > ./.github/cache-version
