# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

set: [pipefail]
shopt: [globstar]

includes:
  tool:
    taskfile: tool.task.yml
    internal: true
  format:
    taskfile: format.task.yml
    internal: true

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    cmds:
    - task: versions
    - task: download
    - task: extract

  versions:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: tool:aqua:tag:coreutils
    - task: tool:aqua:tag:gh
    - task: tool:aqua:tag:jq
    status:
    - |-
      MTIME="$(coreutils stat -c %Y versions.json)"
      NOW="$(coreutils date +%s)"
      AGE="$(coreutils expr "$NOW" - "$MTIME")"
      coreutils test 86400 -gt "$AGE"
    cmds:
    - >-
      gh api repos/woodruffw/zizmor/releases --jq '[.[].name] | {versions: .}' | jq -M > versions.json
    - task: format:biome

  download:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: tool:aqua:tag:jq
    vars:
      VERSION:
        sh: jq -r '.versions | sort_by(sub("^v";"") | split(".") | map(tonumber)) | last' versions.json
    sources:
    - versions.json
    generates:
    - .task/zizmor.tar.gz
    cmds:
    - >-
      curl -fsSLo .task/zizmor.tar.gz
      "https://github.com/woodruffw/zizmor/archive/refs/tags/{{.VERSION}}.tar.gz"

  extract:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    sources:
    - .task/zizmor.tar.gz
    generates:
    - .task/zizmor/Cargo.toml
    cmds:
    - cmd: coreutils mkdir -p .task/zizmor
      silent: true
    - tar -xf .task/zizmor.tar.gz -C .task/zizmor --strip-components 1
