# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

set: [pipefail]
shopt: [globstar]

includes:
  tool:
    taskfile: tool.task.yml
    internal: true

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    cmds:
    - task: download

  download:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: tool:aqua:tag:jq
    vars:
      VERSION:
        sh: jq -r '.versions | sort_by(sub("^v";"") | split(".") | map(tonumber)) | last' versions.json
    sources:
    - versions.json
    generates:
    - .archive/zizmor.tar.gz
    cmds:
    - cmd: coreutils mkdir -p .archive
      silent: true
    # TODO: which curl command
    - >-
      curl -fsSLo .archive/zizmor.tar.gz
      "https://github.com/woodruffw/zizmor/archive/refs/tags/{{.VERSION}}.tar.gz"
