# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  REPOSITORY: woodruffw/zizmor

set: [pipefail]
shopt: [globstar]

includes:
  tool:
    taskfile: tool.task.yml
    internal: true
  format:
    taskfile: format.task.yml
    internal: true

tasks:
  default:
    desc: '{{.TASK}}'
    silent: true
    cmds:
    - task: generate

  generate:
    desc: '{{.TASK}}'
    dir: '{{.ROOT_DIR}}'
    deps:
    - task: tool:aqua:tag:coreutils
    - task: tool:aqua:tag:gh
    - task: tool:aqua:tag:jq
    status:
    - |-
      MTIME="$(coreutils stat -c %Y version.json)"
      NOW="$(coreutils date +%s)"
      AGE="$(coreutils expr "$NOW" - "$MTIME")"
      coreutils test 86400 -gt "$AGE"
    cmds:
    - >-
      gh api 'repos/{{.REPOSITORY}}/releases/latest' --jq '{version: .name}' | jq -M > version.json
    - task: format:biome
