name: autofix.ci
on:
  push:
    branches: ['main']
  pull_request:
permissions:
  contents: read
jobs:
  autofix:
    name: autofix.ci
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.53.9
    - name: Format
      run: task format
    - name: Autofix
      uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27 # v1.3.2
