name: autofix.ci
on:
  push:
    branches: ['main']
  pull_request:
permissions:
  contents: read
jobs:
  autofix:
    name: autofix.ci
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
      with:
        aqua_version: v2.52.0
    - name: Format
      run: task format
    - name: Autofix
      uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944 # v1.3.1
