name: autofix.ci
on:
  push:
    branches: ['main']
  pull_request:
permissions:
  contents: read
jobs:
  autofix:
    name: autofix.ci
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup Aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.51.2
    - name: Format
      run: task format
    - name: Autofix
      uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944 # v1.3.1
