name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
permissions: {}
jobs:
  ##############################################################################
  # Format
  ##############################################################################
  format:
    name: Format
    permissions:
      contents: read
    uses: ./.github/workflows/wc-format.yml
  ##############################################################################
  # Lint
  ##############################################################################
  lint:
    name: Lint
    permissions:
      contents: read
    uses: ./.github/workflows/wc-lint.yml
  ##############################################################################
  # Build
  ##############################################################################
  build:
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/wc-build.yml
  ##############################################################################
  # Status Check
  ##############################################################################
  ci:
    needs:
    - format
    - lint
    - build
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: ${{ failure() || cancelled() }}
    steps:
    - name: Failure Status
      run: exit 1
