name: CI
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
    inputs:
      build-version:
        description: "Build version"
        default: ""
        required: false
        type: string
permissions: {}
jobs:
  ##############################################################################
  # Format
  ##############################################################################
  format:
    name: Format
    permissions:
      contents: read
    uses: ./.github/workflows/wc-format.yml
  ##############################################################################
  # Lint
  ##############################################################################
  lint:
    name: Lint
    permissions:
      contents: read
    uses: ./.github/workflows/wc-lint.yml
  ##############################################################################
  # Setup
  ##############################################################################
  setup:
    name: Setup
    permissions:
      contents: read
    uses: ./.github/workflows/wc-setup.yml
    with:
      build-version: ${{ github.event.inputs.build-version }}
  ##############################################################################
  # Build
  ##############################################################################
  build:
    needs:
    - setup
    name: Build
    permissions:
      contents: read
    uses: ./.github/workflows/wc-build.yml
    with:
      build-version: ${{ needs.setup.outputs.build-version }}
  ##############################################################################
  # Sign
  ##############################################################################
  sign:
    needs:
    - setup
    - build
    name: Sign
    permissions:
      id-token: write
      attestations: write
    uses: ./.github/workflows/wc-sign.yml
  ##############################################################################
  # Release
  ##############################################################################
  release:
    needs:
    - setup
    - build
    - sign
    name: Release
    permissions:
      contents: write
    uses: ./.github/workflows/wc-release.yml
    with:
      build-version: ${{ needs.setup.outputs.build-version }}
  ##############################################################################
  # Status Check
  ##############################################################################
  ci:
    needs:
    - format
    - lint
    - setup
    - build
    - sign
    - release
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: ${{ failure() || cancelled() }}
    steps:
    - name: Failure Status
      run: exit 1
