name: Version
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Tag version"
        default: ""
        required: false
        type: string
permissions:
  contents: read
jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    environment:
      name: version
    steps:
    - name: Create GitHub App Token
      uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
        permission-contents: write
    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
    - id: committer
      run: echo "string=${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"  >> "$GITHUB_OUTPUT"
    - run: echo "committer string is ${{ steps.committer.outputs.string }}"
