name: Lint
on:
  workflow_call:
permissions: {}
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      targets: ${{ steps.matrix.outputs.result }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
        sparse-checkout: |-
          .aqua
          tasks
    - name: Setup aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.51.1
    - name: Generate Matrix
      id: matrix
      # TODO: set BUILD_VERSION
      # env:
      #   BUILD_VERSION: TODO
      run: echo "result=$(task build:matrix)" >> "$GITHUB_OUTPUT"
    - name: Check Matrix
      env:
        BUILD_MATRIX: ${{ steps.matrix.outputs.result }}
      run: |-
        echo "${BUILD_MATRIX}" | jq
  build:
    needs: matrix
    name: ${{ matrix.version }} / ${{ matrix.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
      attestations: write
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.targets) }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.51.1
    - name: Restore aqua tools cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: aqua-${{ hashFiles('.aqua/pkgs/cargo-zigbuild.yaml', '.aqua/pkgs/rustup.yaml', '.aqua/pkgs/zig.yaml') }}
        path: ~/.local/share/aquaproj-aqua/
    - name: Restore cargo deps cache
      id: deps-cache-restore
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: deps-${{ matrix.version }}-${{ hashFiles('.github/cache-version') }}
        path: ~/.cargo/registry/
    - name: Restore build cache
      id: build-cache-restore
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: build-${{ matrix.version }}-${{ matrix.target }}-${{ hashFiles('.github/cache-version') }}
        path: .build/
    - name: Build ${{ matrix.version }}/${{ matrix.target }}
      run: |-
        task build
      env:
        CARGO_INCREMENTAL: ${{ startsWith(github.ref, 'refs/tag/') && '0' || '1' }}
        BUILD_TARGET: ${{ matrix.target }}
        # BUILD_VERSION: TODO
    - name: Save build cache
      if: github.ref == 'refs/heads/main' && steps.build-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}
        path: .build/
