name: Build
on:
  workflow_call:
    inputs:
      build-version:
        default: ""
        required: false
        type: string
permissions: {}
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  matrix:
    name: Matrix
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    env:
      BUILD_VERSION: ${{ inputs.build-version }}
    outputs:
      targets: ${{ steps.matrix.outputs.result }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
        sparse-checkout: |-
          .aqua
          tasks
    - name: Setup aqua
      uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
      with:
        aqua_version: v2.51.2
    - name: Check valid version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash -euo pipefail {0}
      run: |-
        task version:check
    - name: Generate matrix
      id: matrix
      shell: bash -euo pipefail {0}
      run: |-
        echo "result=$(task build:matrix)" >> "$GITHUB_OUTPUT"
    - name: Check matrix
      env:
        BUILD_MATRIX: ${{ steps.matrix.outputs.result }}
      shell: bash -euo pipefail {0}
      run: |-
        echo "${BUILD_MATRIX}" | jq
  build:
    needs: matrix
    name: ${{ matrix.version }} / ${{ matrix.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix.outputs.targets) }}
    env:
      BUILD_TARGET: ${{ matrix.target }}
      BUILD_VERSION: ${{ matrix.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
      with:
        aqua_version: v2.51.2
    - name: Restore aqua tools cache
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: aqua-${{ hashFiles('.aqua/pkgs/cargo-zigbuild.yaml', '.aqua/pkgs/rustup.yaml', '.aqua/pkgs/zig.yaml') }}
        path: ~/.local/share/aquaproj-aqua/
    - name: Restore cargo deps cache
      id: deps-cache-restore
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: deps-${{ matrix.version }}-${{ hashFiles('.github/cache-version') }}
        path: ~/.cargo/registry/
    - name: Restore build cache
      id: build-cache-restore
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: build-${{ matrix.version }}-${{ matrix.target }}-${{ hashFiles('.github/cache-version') }}
        path: .build/
    - name: Build binary
      env:
        CARGO_INCREMENTAL: ${{ startsWith(github.ref, 'refs/tag/') && '0' || '1' }}
      shell: bash -euo pipefail {0}
      run: |-
        task build:binary
    - name: Generate sha256sum
      shell: bash -euo pipefail {0}
      run: |-
        task build:sha256sum:verify
    - name: Get latest version
      id: latest_version
      shell: bash -euo pipefail {0}
      run: echo "result=$(task version:latest)" >> "$GITHUB_OUTPUT"
    - name: Save build cache
      if: >-
        github.ref == 'refs/heads/main'
        && steps.build-cache-restore.outputs.cache-hit != 'true'
        && steps.latest_version.outputs.result == env.BUILD_VERSION
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}
        path: .build/
    - name: Get artifact name
      id: artifact_name
      shell: bash -euo pipefail {0}
      run: echo "result=$(task build:name)" >> "$GITHUB_OUTPUT"
    - name: Get binary name
      id: binary_name
      shell: bash -euo pipefail {0}
      run: echo "result=$(task build:binname)" >> "$GITHUB_OUTPUT"
    - name: Get binary path
      id: binary_path
      shell: bash -euo pipefail {0}
      run: echo "result=$(task build:binpath)" >> "$GITHUB_OUTPUT"
    - name: Upload artifact
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: artifact-${{ steps.artifact_name.outputs.result }}
        path: |-
          ${{ steps.binary_path.outputs.result }}
          ${{ steps.binary_path.outputs.result }}.sha256sum
