name: Cache
on:
  workflow_call:
permissions: {}
concurrency:
  group: cache-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  cache:
    name: Cache
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
        sparse-checkout: |-
          .aqua
          tasks
    - name: Setup aqua
      uses: aquaproj/aqua-installer@5e54e5cee8a95ee2ce7c04cb993da6dfad13e59c # v3.1.2
      with:
        aqua_version: v2.51.1
    - name: Restore setup build aqua cache
      id: aqua-cache-restore
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: aqua-${{ hashFiles('.aqua/pkgs/cargo-zigbuild.yaml', '.aqua/pkgs/rustup.yaml', '.aqua/pkgs/zig.yaml') }}
        path: ~/.local/share/aquaproj-aqua/
    - name: Fetch aqua tools
      run: |-
        task tool:aqua:tag:rustup
        task tool:aqua:tag:cargo-zigbuild
        task tool:aqua:tag:zig
    - name: Save setup build aqua cache
      if: github.ref == 'refs/heads/main' && steps.aqua-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        key: ${{ steps.aqua-cache-restore.outputs.cache-primary-key }}
        path: ~/.local/share/aquaproj-aqua/
