name: Format
on:
  workflow_call:
permissions: {}
concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
      with:
        aqua_version: v2.52.0
    - name: Format files
      shell: bash -euo pipefail {0}
      run: |-
        task format
    - name: Detected changes
      shell: bash -euo pipefail {0}
      run: |-
        git reset
        git -c core.fileMode=false add --all
        git diff --name-only --staged --no-renames --exit-code
