name: Format
on:
  workflow_call:
permissions: {}
concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
      with:
        aqua_version: v2.54.0
    - name: Format files
      shell: bash -euo pipefail {0}
      run: |-
        task format
    - name: Detected changes
      shell: bash -euo pipefail {0}
      run: |-
        git reset
        git -c core.fileMode=false add --all
        git diff --name-only --staged --no-renames --exit-code
