name: Format
on:
  workflow_call:
permissions: {}
concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@5c140f8fcd4035d84e5d893f1e4a9dc1283e1e4a # v4.0.1
      with:
        aqua_version: v2.53.3
    - name: Format files
      shell: bash -euo pipefail {0}
      run: |-
        task format
    - name: Detected changes
      shell: bash -euo pipefail {0}
      run: |-
        git reset
        git -c core.fileMode=false add --all
        git diff --name-only --staged --no-renames --exit-code
