name: Lint
on:
  workflow_call:
permissions: {}
concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        persist-credentials: false
    - name: Setup aqua
      uses: aquaproj/aqua-installer@d1fe50798dbadd4eb5b98957290ca175f6b4870f # v4.0.2
      with:
        aqua_version: v2.53.9
    - name: Lint files
      shell: bash -euo pipefail {0}
      run: |-
        task lint
