name: Release
on:
  workflow_call:
permissions: {}
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        path: dist/
        name: release-signed-artifacts
    - name: Check artifacts
      run: tree --charset ASCII dist/
    - name: Verify sha256sums
      run: |-
        echo 'Verify sha256sums'
        cd dist
        sha256sum -c SHA256SUMS
    - name: Verify artifact attestation
      if: ${{ !startsWith(github.event_name, 'pull') }}
      run: |
        echo 'Verify artifact attestation'
        cd dist
        # for f in $(find . -type f -not -name '*.cert' -a -not -name '*.sig' -printf '%f\n' | sort); do
        #   gh attestation verify "$f" -R "${GITHUB_REPOSITORY}";
        # done
        # check failed
        for f in $(find . -type f -not -name '*.cert' -a -not -name '*.sig' -printf '%f\n' | sort); do
          gh attestation verify "$f" -R "${GITHUB_REPOSITORY}";
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
