name: Release
on:
  workflow_call:
permissions: {}
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        path: dist/
        name: release-artifacts
    - name: Check artifacts
      shell: bash -euo pipefail {0}
      run: tree --charset ASCII dist/
    - name: Verify sha256sums
      shell: bash -euo pipefail {0}
      run: |-
        echo 'Verify sha256sums'
        cd dist
        sha256sum -c SHA256SUMS || exit 1
    - name: Verify artifact attestation
      if: ${{ !startsWith(github.event_name, 'pull') }}
      shell: bash -euo pipefail {0}
      run: |-
        echo 'Verify artifact attestation'
        cd dist
        for f in $(find . -type f -not -name '*.cert' -a -not -name '*.sig' -printf '%f\n' | sort); do
          gh attestation verify "$f" -R "${GITHUB_REPOSITORY}";
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup cosign
      if: ${{ !startsWith(github.event_name, 'pull') }}
      uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
    - name: Verify code signing with cosign
      if: ${{ !startsWith(github.event_name, 'pull') }}
      env:
        CERTIFICATE_IDENTITY: >-
          '${{ github.server_url }}/${{ github.repository }}/.github/workflows/wc-sign.yml@${{ github.ref }}'
        CERTIFICATE_OIDC_ISSUER: 'https://token.actions.githubusercontent.com'
      shell: bash -euo pipefail {0}
      run: |-
        echo 'Verify code signing with cosign'
        cd dist
        for f in $(find . -type f -not -name '*.cert' -a -not -name '*.sig' -printf '%f\n' | sort); do
          cosign verify-blob "$f" \
            --certificate "$f.cert" \
            --signature "$f.sig" \
            --certificate-identity "$CERTIFICATE_IDENTITY" \
            --certificate-oidc-issuer "$CERTIFICATE_OIDC_ISSUER" \
          ;
        done
