name: Sign
on:
  workflow_call:
permissions: {}
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  sign:
    name: Sign
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      attestations: write
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        path: dist/
        pattern: artifact-*
        merge-multiple: true
    - name: Check artifacts
      run: tree --charset ASCII dist/
    - name: Verify sha256sum
      run: |-
        echo 'Verify sha256sum'
        cd dist
        for f in $(find . -type f -name '*.sha256sum' -printf '%f\n' | sort); do
          sha256sum -c "$f";
        done
    - name: Generate artifact attestation
      if: ${{ !startsWith(github.event_name, 'pull') }}
      uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
      with:
        subject-path: 'dist/*'
    - name: Setup cosign
      if: ${{ !startsWith(github.event_name, 'pull') }}
      uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb # v3.8.2
    - name: Generate code signing with cosign
      if: ${{ !startsWith(github.event_name, 'pull') }}
      run: |-
        echo 'Generate code signing with cosign'
        cd dist
        for f in $(find . -type f -printf '%f\n' | sort); do
          cosign sign-blob "$f" -y --output-certificate "$f.cert" --output-signature "$f.sig";
        done
    - name: Check artifacts
      run: tree --charset ASCII dist/
    - name: Upload artifacts
      if: ${{ !startsWith(github.event_name, 'pull') }}
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: signed-artifacts
        path: |-
          dist/*.cert
          dist/*.sig
