name: Sign
on:
  workflow_call:
permissions: {}
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  sign:
    name: Sign
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      id-token: write
      attestations: write
    steps:
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        path: dist/
        pattern: artifact-*
        merge-multiple: true
    - name: Verify sha256sum
      run: |-
        cd dist
        for f in $(find . -type f -name '*.sha256sum' -printf '%f\n' | sort); do
          sha256sum -c "$f";
        done
    # TODO
    # - name: Generate cosign
    #   if: ${{ !startsWith(github.event_name, 'pull') }}
    #   env:
    #     CERTIFICATE_IDENTITY: >-
    #       '${{ github.server_url }}/${{ github.repository }}/.github/workflows/wc-build.yml@${{ github.ref }}'
    #     CERTIFICATE_OIDC_ISSUER: 'https://token.actions.githubusercontent.com'
    #   run: |-
    #     task build:cosign:verify
    # - name: Generate artifact attestation
    #   if: ${{ !startsWith(github.event_name, 'pull') }}
    #   uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
    #   with:
    #     subject-name: ${{ steps.artifact_name.outputs.result }}
    #     subject-path: ${{ steps.binary_path.outputs.result }}
    - name: Check artifacts
      run: tree --charset ASCII dist/
