name: Setup
on:
  workflow_call:
    inputs:
      build-version:
        default: ""
        required: false
        type: string
    outputs:
      build-version:
        value: ${{ jobs.setup.outputs.version }}
permissions: {}
concurrency:
  group: setup-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    env:
      BUILD_VERSION: ${{ inputs.build-version }}
    outputs:
      version: ${{ steps.version.outputs.result }}
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
        sparse-checkout: |-
          .aqua
          .github
          tasks
    - name: Setup aqua
      uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
      with:
        aqua_version: v2.53.9
    - name: Check valid version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash -euo pipefail {0}
      run: |-
        task version:check
    - name: Get build version
      id: version
      shell: bash -euo pipefail {0}
      run: echo "result=$(task build:version)" >> "$GITHUB_OUTPUT"
    - name: Restore setup build aqua cache
      id: aqua-cache-restore
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        key: aqua-${{ hashFiles('.aqua/pkgs/cargo-zigbuild.yaml', '.aqua/pkgs/rustup.yaml', '.aqua/pkgs/zig.yaml') }}
        path: ~/.local/share/aquaproj-aqua/
    - name: Restore cargo deps cache
      id: deps-cache-restore
      uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        key: deps-${{ steps.version.outputs.result }}-${{ hashFiles('.github/cache-version') }}
        path: ~/.cargo/registry/
    - name: Fetch aqua tools
      shell: bash -euo pipefail {0}
      run: |-
        task tool:aqua:tag:rustup
        task tool:aqua:tag:cargo-zigbuild
        task tool:aqua:tag:zig
    - name: Fetch cargo deps
      shell: bash -euo pipefail {0}
      run: |-
        task build:fetch
    - name: Save cargo deps cache
      if: github.ref == 'refs/heads/main' && steps.deps-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        key: ${{ steps.deps-cache-restore.outputs.cache-primary-key }}
        path: ~/.cargo/registry/
    - name: Save setup build aqua cache
      if: github.ref == 'refs/heads/main' && steps.aqua-cache-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        key: ${{ steps.aqua-cache-restore.outputs.cache-primary-key }}
        path: ~/.local/share/aquaproj-aqua/
